name: Deploy MkDocs site

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material

      - name: Build MkDocs site
        run: mkdocs build
      
      - name: Deploy using ghp-import
        run: |
          pip install ghp-import
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          ghp-import -n -p -f -r "https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/AndyMRoberts/my-first-website.git" site

